name: vshivpuri
favicon: null
layout_spectrum: 0.48492005257867277
typography_spectrum: 0.15339166368357837
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5991070775780827
  lightness: 0.9204100749921054
  saturation: 0.8848140605259687
  rhythmicContrast: 0.4027736207935959
purpose: []
