name: vshivpuri
favicon: null
layout_spectrum: 0.48492005257867277
typography_spectrum: 0.15339166368357837
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0093b9'
    - '#22334b'
    - '#ffffff'
    - '#80ffff'
    - '#aaaaaa'
  brandStrength: 0.375
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
